### PR TITLE
add NoteActivity [AA,RH]

### PR DESCRIPTION
**Pull request by haubitzer**

### CODE REVIEW

**Comment by tinabambina** [comment]
Text does not wrap properly in the title as well as in the content box. 
You need to use "match_parent" as the layout width properties I guess.

**Comment by anhaupt** [comment]
Maybe we should limit the title to a fixed number of chars. Than it is also more easy to display it in the overview list.

**Comment by awgrass** [comment]
> Maybe we should limit the title to a fixed number of chars. Than it is also more easy to display it in the overview list.

No, I don't see why we should limit the user. But similar to what you proposed, we should clip the title in the overview after a fixed amount of letters. So we only display the first 30 chars or something like that. 

Nevertheless this doesn't solve your problem in the content box. As Tina said, try to match the parent's container width.

**Comment by agape94** [comment]
> Text does not wrap properly in the title as well as in the content box.
> You need to use "match_parent" as the layout width properties I guess.

I don't see any problems with the title.
Fixed issues with content edittext. Fixed scrolling in the content edittext.

**Comment by haubitzer** [comment]
@anhaupt  just do it

**Review by anhaupt — APPROVED** [review]
now it looks good - good job guys

**Pull request merged**
